#!/bin/bash
docker run --rm \
           --name jenkins \
           -p 8080:8080 \
           -p 50000:50000 \
           --volume ~/workspace/nanny/jenkins_home:/var/jenkins_home \
           --volume "$HOME":/home \
           jenkins/jenkins:lts-jdk11
