#!/bin/bash
docker run --rm \
           --name jenkins \
           --privileged \
           --rm \
           --net=host \
           --volume ~/workspace/jenkins:/var/jenkins_home \
           --volume "$HOME":/home \
           --volume /var/run/docker.sock:/var/run/docker.sock \
           --volume /usr/bin/docker:/usr/bin/docker \
           --volume "$HOME/.docker":"$HOME/.docker" \
           jenkins/jenkins:lts-jdk11
