#!/bin/bash
sudo cp /home/pi/services/stream_camera.service /etc/systemd/system/stream_camera.service
sudo systemctl daemon-reload
sudo systemctl restart stream_camera.service
echo Updated and restarted stream_camera.service
