#!/bin/bash
sudo cp /home/pi/services/save_audio.service /etc/systemd/system/save_audio.service
sudo systemctl daemon-reload
sudo systemctl restart save_audio.service
echo Updated and restarted save_audio.service
