#!/bin/bash
set -e

SSH_SOURCE_FOLDER="/home/.ssh"
# SSH_DESTINATION_FOLDER="/home/$USER/.ssh"
SSH_DESTINATION_FOLDER="/root/.ssh"
ls -la $SSH_SOURCE_FOLDER
if [ -d "$SSH_SOURCE_FOLDER" ]; then
    echo Changing permissions of "$SSH_SOURCE_FOLDER" to "$SSH_DESTINATION_FOLDER"
    cp -R "$SSH_SOURCE_FOLDER" "$SSH_DESTINATION_FOLDER"
    chmod 700 "$SSH_DESTINATION_FOLDER"
    chmod 644 "$SSH_DESTINATION_FOLDER/id_rsa.pub"
    chmod 600 "$SSH_DESTINATION_FOLDER/id_rsa"
else
    echo "$SSH_SOURCE_FOLDER" does not exist
fi
exec "$@"
