#!/bin/bash
set -e

SSH_SOURCE_FOLDER="/tmp/.ssh"
SSH_DESTINATION_FOLDER="/home/$USER/.ssh"
if [ -f "$SSH_SOURCE_FOLDER" ]; then
    cp -R /tmp/.ssh "$SSH_DESTINATION_FOLDER"
    chmod 700 "$SSH_DESTINATION_FOLDER"
    chmod 644 "$SSH_DESTINATION_FOLDER/id_rsa.pub"
    chmod 600 "$SSH_DESTINATION_FOLDER/.ssh/id_rsa"
fi
exec "$@"
